eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
service:
  port: 7777
spring:
  application:
    name: cloud-config-server

demo:
  param1: 龙磊是个大傻逼.............test
